# Generated by Django 3.1.3 on 2020-11-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='balcony',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
