# Generated by Django 3.1.3 on 2020-11-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhome', '0002_home_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='status',
            field=models.CharField(default='Awaiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='home',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
