# Generated by Django 3.1.3 on 2020-11-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhome', '0004_home_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
