# Generated by Django 3.1.3 on 2020-11-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhome', '0005_auto_20201122_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='pic',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
